version: 2.1
orbs:
  android: circleci/android@2.4.0
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.09
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /opt/android/sdk  # Ensure the correct SDK path
      PATH: /opt/android/sdk/platform-tools:/opt/android/sdk/tools:$PATH  # Add sdk tools to PATH

jobs:
  build:
    docker:
      - image: openjdk:17-jdk  # Use official OpenJDK 17 image
    working_directory: ~/AndroidStudioProjects/Lab08_NEW
    steps:
      - checkout
      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build and Test
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle.kts" }}

  unit_tests:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: unit_test_reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
      - build:
          requires:
            - unit_tests
